---
- name: 
  hosts: all
  become: true
  vars:
    git_repository: https://github.com/1wonderwonder/Ansible_roles.git
    git_branch: "main"

  tasks:

  - name: Create a directory for Ansible roles
    file:
      path: /etc/ansible/roles
      state: directory
      mode: '0755'
  - name: Git checkout
  
    git:
      repo: "{{ git_repository }}"
      dest: "/etc/ansible/roles"
      version: "{{ git_branch }}"